/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: CN Entertainment (https://sketchfab.com/cn-entertainment)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/kallax-shelf-e2d30124563947608a500df26f77b659
title: Kallax Shelf
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("models/shelf/model-transformed.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group
            position={[0, 100, -200]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={250}
          >
            <mesh
              geometry={nodes.Cube_White_0.geometry}
              material={materials.White}
              metalness={0.2}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("models/shelf/model-transformed.glb");
